# Generated by Django 3.1.6 on 2021-12-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0006_requiredfieldsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditingBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccreditingBody', models.BooleanField(default='False', verbose_name='Accrediting Body')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='accreditingBody',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentversion',
            name='accreditingBody',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='users',
            field=models.CharField(blank=True, default='------', max_length=100),
        ),
        migrations.AddField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default='2021-12-02'),
        ),
        migrations.AddField(
            model_name='sloinreport',
            name='accreditingBody',
            field=models.BooleanField(default=False, verbose_name='Accrediting_body'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='directMeasure',
            field=models.BooleanField(default=False, verbose_name='direct measure'),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='allStudents',
            field=models.BooleanField(default='False', verbose_name='all students assessed'),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='target',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
