# Generated by Django 3.1.6 on 2021-10-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0006_requiredfieldsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditingBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccreditingBody', models.BooleanField(default='False')),
            ],
        ),
    ]
