# Generated by Django 3.1.6 on 2021-12-02 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0007_auto_20211202_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 14, 44, 43, 211921, tzinfo=utc)),
        ),
    ]
