# Generated by Django 3.1.6 on 2021-12-04 01:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0007_auto_20211203_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='users',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 4, 1, 58, 52, 517613, tzinfo=utc)),
        ),
    ]
