# Generated by Django 3.1.6 on 2021-12-02 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0008_auto_20211202_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='accreditingBodyPrograms',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 20, 34, 42, 215659, tzinfo=utc)),
        ),
    ]
