# Generated by Django 3.1.6 on 2021-11-09 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0008_auto_20211005_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slo',
            name='accreditingBody',
        ),
        migrations.AddField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sloinreport',
            name='accreditingBody',
            field=models.BooleanField(default=False, verbose_name='Accrediting_body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sloinreport',
            name='accreditingBodyDomain',
            field=models.CharField(choices=[('', '------'), ('PF', 'Performance'), ('PD', 'Product'), ('EX', 'Examination')], default=False, max_length=50, verbose_name='Accrediting Body Domain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sloinreport',
            name='accreditingBodyMeasures',
            field=models.CharField(choices=[('', '------'), ('DM', 'Direct Measure'), ('IM', 'Indirect Measure')], default=False, max_length=50, verbose_name='Accrediting Measures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sloinreport',
            name='accreditingBodyText',
            field=models.CharField(default=False, max_length=1000, verbose_name='AccreditingBodyText'),
            preserve_default=False,
        ),
    ]
