# Generated by Django 3.1.6 on 2021-11-06 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0008_auto_20211005_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slo',
            name='accreditingBody',
        ),
        migrations.AddField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sloinreport',
            name='accreditingBody',
            field=models.BooleanField(default=1, verbose_name='Accrediting_body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sloinreport',
            name='accreditingBodyMeasures',
            field=models.CharField(choices=[('', '------'), ('PF', 'Performance'), ('PD', 'Product'), ('EX', 'Examination')], default=1, max_length=50, verbose_name='Accrediting Measures'),
            preserve_default=False,
        ),
    ]
