# Generated by Django 3.1.6 on 2021-12-04 23:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0009_auto_20211203_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 4, 23, 33, 17, 609633, tzinfo=utc)),
        ),
    ]
