# Generated by Django 3.1.6 on 2021-12-02 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0009_auto_20211202_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='slostostakeholder',
            name='faculty',
            field=models.BooleanField(default=False, verbose_name='Faculty/Staff'),
        ),
        migrations.AddField(
            model_name='slostostakeholder',
            name='students',
            field=models.BooleanField(default=False, verbose_name='Faculty/Staff'),
        ),
        migrations.AlterField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 21, 12, 21, 618948, tzinfo=utc)),
        ),
    ]
