# Generated by Django 3.1.6 on 2021-11-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0009_auto_20211108_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sloinreport',
            name='accreditingBodyDomain',
        ),
        migrations.RemoveField(
            model_name='sloinreport',
            name='accreditingBodyMeasures',
        ),
        migrations.RemoveField(
            model_name='sloinreport',
            name='accreditingBodyText',
        ),
        migrations.AlterField(
            model_name='sloinreport',
            name='accreditingBody',
            field=models.BooleanField(default=False, verbose_name='Accrediting_body'),
        ),
    ]
