# Generated by Django 3.1.6 on 2021-12-05 21:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0010_auto_20211204_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='slo',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slo',
            name='importedFrom',
            field=models.CharField(default='', max_length=50, verbose_name='imported SLO'),
        ),
        migrations.AlterField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 5, 21, 2, 53, 675469, tzinfo=utc)),
        ),
    ]
