# Generated by Django 3.1.6 on 2021-12-02 21:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0010_auto_20211202_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 21, 22, 24, 485878, tzinfo=utc)),
        ),
    ]
