# Generated by Django 3.1.6 on 2021-12-02 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0011_auto_20211202_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='slostostakeholder',
            name='other_internal',
            field=models.BooleanField(default=False, verbose_name='Other-internal'),
        ),
        migrations.AlterField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 21, 41, 26, 536324, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='slostostakeholder',
            name='students',
            field=models.BooleanField(default=False, verbose_name='Students'),
        ),
    ]
