# Generated by Django 3.1.6 on 2021-12-02 21:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0012_auto_20211202_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='slostostakeholder',
            name='alumni',
            field=models.BooleanField(default=False, verbose_name='Alumni'),
        ),
        migrations.AddField(
            model_name='slostostakeholder',
            name='community_members',
            field=models.BooleanField(default=False, verbose_name='Community Members'),
        ),
        migrations.AddField(
            model_name='slostostakeholder',
            name='employers',
            field=models.BooleanField(default=False, verbose_name='Employers'),
        ),
        migrations.AddField(
            model_name='slostostakeholder',
            name='other_external',
            field=models.BooleanField(default=False, verbose_name='Other-External'),
        ),
        migrations.AddField(
            model_name='slostostakeholder',
            name='prospect_students',
            field=models.BooleanField(default=False, verbose_name='Prospective Students'),
        ),
        migrations.AlterField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 21, 52, 34, 430199, tzinfo=utc)),
        ),
    ]
