# Generated by Django 3.1.6 on 2021-11-09 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0012_sloinreport_accreditingbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAccreditingBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('frequencyChoice', models.CharField(choices=[('S', 'Once/semester'), ('Y', 'Once/year'), ('O', 'Other')], default='O', max_length=100, verbose_name='frequency choice')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.report')),
                ('slo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.sloinreport', verbose_name='SLO in report')),
            ],
        ),
    ]
