# Generated by Django 3.1.6 on 2021-11-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0013_auto_20211109_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentversion',
            name='allStudents',
            field=models.BooleanField(default=False, verbose_name='all students assessed'),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='target',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
