# Generated by Django 3.1.6 on 2021-12-02 23:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0013_auto_20211202_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 23, 56, 39, 592217, tzinfo=utc)),
        ),
    ]
