# Generated by Django 3.1.6 on 2021-11-09 07:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0013_assessmentaccreditingbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentaccreditingbody',
            name='title',
        ),
        migrations.AddField(
            model_name='assessmentaccreditingbody',
            name='allStudents',
            field=models.BooleanField(default=django.utils.timezone.now, verbose_name='all students assessed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentaccreditingbody',
            name='assessment',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='makeReports.assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentaccreditingbody',
            name='changedFromPrior',
            field=models.BooleanField(default=django.utils.timezone.now, verbose_name='changed from prior version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentaccreditingbody',
            name='finalTerm',
            field=models.BooleanField(default=django.utils.timezone.now, verbose_name='final term'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentaccreditingbody',
            name='frequency',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentaccreditingbody',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentaccreditingbody',
            name='sampleDescription',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description of sample'),
        ),
        migrations.AddField(
            model_name='assessmentaccreditingbody',
            name='supplements',
            field=models.ManyToManyField(to='makeReports.AssessmentSupplement'),
        ),
        migrations.AddField(
            model_name='assessmentaccreditingbody',
            name='target',
            field=models.PositiveIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentaccreditingbody',
            name='threshold',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentaccreditingbody',
            name='where',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='location of assessment'),
            preserve_default=False,
        ),
    ]
