# Generated by Django 3.1.6 on 2021-11-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0013_auto_20211111_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentversion',
            name='accreditingBody',
            field=models.BooleanField(default=False),
        ),
    ]
