# Generated by Django 3.1.6 on 2021-12-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0013_auto_20211111_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='slo',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slo',
            name='importedFrom',
            field=models.CharField(default='', max_length=50, verbose_name='imported SLO'),
        ),
    ]
