# Generated by Django 3.1.6 on 2021-11-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0009_auto_20211105_2127'),
        ('makeReports', '0013_auto_20211111_2209'),
    ]

    operations = [
    ]
