# Generated by Django 3.1.6 on 2021-12-03 00:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0014_auto_20211202_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultcommunicate',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 0, 2, 19, 2762, tzinfo=utc)),
        ),
    ]
